# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "VIA-TARIQ"
email: "a.pazout@seznam.cz"
name: "Adam Pažout"
description: "Research on Roman, Medieval, and Ottoman transport networks in the Levant"
baseurl: "" # the subpath of your site
url: "https://pazadam.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: Archaeologue1
#github_username:  pazadam

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
plugins:
  - jekyll-feed
  - jekyll-include-cache

skin: "dirt" # using the 'dirt' skin for a nice earthy look

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

#Site author
author:
  name: "Adam Pažout"
  avatar: "/assets/images/avatar.png"
  bio: "I am MSCA Fellow at the Universitat Autònoma de Barcelona with project 'VIA-TARIQ: Analysing long-term change and persistency of the Roman road system in the Levant.' My research interests are Roman and post-Roman roads, development of settlement structures, economic history, as well as landscape archaeology and digital methods in archaeological research in general (predominantly GIS and network science)."
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:a.pazout@seznam.cz"

    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/pazadam"

    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/Archaeologue1"

defaults:
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: single
      author_profile: true
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: single # this can be 'single', 'archive', etc.
      author_profile: true

navigation:
  enabled: true
  data: navigation

collections:
  pages:
    output: true
    permalink: /:name/
  posts:
    output: true
    permalink: /news/:year/:month/:day/:title/

# Sidebar settings
sidebar:
  nav: "main"

paginate: 5
paginate_path: "/page:num/"